@startuml dependances_composants
title Components dependencies

package "Page sondage" {
    component sondage
    component option_reponse
    component voir_reponse_option
    component bouton_voir_tout
    component auteur_sondage
    }
package "Page reponse" {
    component reponse_dev
    component personne_sondee
    component bouton_fermer_reponse
    }

sondage "1"-->"+" option_reponse: "contient"
sondage "1"-->"1" auteur_sondage: "contient"
sondage "1"-->"0-1" bouton_voir_tout
option_reponse "1" --> "1" voir_reponse_option
voir_reponse_option "1" --> "1" reponse_dev
reponse_dev "+" --> "*" personne_sondee
reponse_dev "1" --> "1" bouton_fermer_reponse

@enduml